name: Build MIR for Windows and Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize and update git submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Set up .NET SDK 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
      
      - name: Patch Harmony
        working-directory: ./src/Harmony/Harmony
        run: |
          dotnet add package MonoMod
          dotnet add package MonoMod.Core
          dotnet build -f net9.0

      - name: Build the project for Linux
        working-directory: ./src/MadnessInteractiveReloaded
        run: dotnet build --runtime linux-x64 -c Release
          # dotnet build --configuration Release # for some reason fails
      
      # - name: Build the project for Windows
      #   working-directory: ./src/MadnessInteractiveReloaded
      #   run: dotnet build --runtime win-x64 -c Release

      - name: Compress artifacts
        working-directory: ./src/MadnessInteractiveReloaded/bin/Release/net9.0/linux-x64
        run: |
          tar cf - linux-x64/ | xz -z - > MIR-linux-x64.tar.xz

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: MIR-linux-x64.tar.xz
          path: |
            ./src/MadnessInteractiveReloaded/bin/Release/net9.0/MIR-linux-x64.tar.xz
